import { RedactoConfig, ComplianceType, BannerPosition } from "../types";
export declare const defaultBannerConfig: {
    position: BannerPosition;
    primaryColor: string;
    backgroundColor: string;
    textColor: string;
    acceptButtonColor: string;
    acceptButtonTextColor: string;
    rejectButtonColor: string;
    rejectButtonTextColor: string;
    manageButtonColor: string;
    manageButtonTextColor: string;
    borderRadius: string;
    fontSize: string;
    fontFamily: string;
    padding: string;
    margin: string;
    zIndex: number;
    showIcon: boolean;
    iconPosition: "left";
    animation: "slide";
    animationDuration: number;
};
export declare const defaultModalConfig: {
    backgroundColor: string;
    overlayColor: string;
    textColor: string;
    primaryColor: string;
    secondaryColor: string;
    borderRadius: string;
    fontSize: string;
    fontFamily: string;
    padding: string;
    maxWidth: string;
    maxHeight: string;
    zIndex: number;
    animation: "scale";
    animationDuration: number;
};
export declare const defaultTexts: {
    bannerTitle: string;
    bannerDescription: string;
    acceptAllText: string;
    rejectAllText: string;
    managePreferencesText: string;
    modalTitle: string;
    modalDescription: string;
    necessaryTitle: string;
    necessaryDescription: string;
    functionalTitle: string;
    functionalDescription: string;
    analyticsTitle: string;
    analyticsDescription: string;
    advertisingTitle: string;
    advertisingDescription: string;
    socialTitle: string;
    socialDescription: string;
    otherTitle: string;
    otherDescription: string;
    savePreferencesText: string;
    privacyPolicyText: string;
    cookiePolicyText: string;
    poweredByText: string;
};
export declare const defaultServices: any[];
export declare const createDefaultConfig: (complianceType?: ComplianceType) => RedactoConfig;
//# sourceMappingURL=defaults.d.ts.map